<?php

use Illuminate\Database\Seeder;

class MenuitemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('menuitem')->insert(array(


              // Snacks
              array(
                'naam' => 'Organic Yoghurt',
                'beschrijving' => 'With granola & jam',
                'allergenen' => '',
                'categorie' => 'Snacks',
                'diet' => '',
                'prijs' => '4.00',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Daily Two',
                'beschrijving' => 'Pieces of fruit',
                'allergenen' => '',
                'categorie' => 'Snacks',
                'diet' => '',
                'prijs' => '1.50',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Smoothie',
                'beschrijving' => 'With forest fruits & yoghurt',
                'allergenen' => '',
                'categorie' => 'Snacks',
                'diet' => '',
                'prijs' => '3.50',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Breakfast Cocktail',
                'beschrijving' => 'with oats, mango & banana',
                'allergenen' => '',
                'categorie' => 'Snacks',
                'diet' => '',
                'prijs' => '3.50',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Oat Cookie',
                'beschrijving' => 'Homemade',
                'allergenen' => '',
                'categorie' => 'Snacks',
                'diet' => '',
                'prijs' => '1.50',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Croissant',
                'beschrijving' => 'Freshly baked',
                'allergenen' => '',
                'categorie' => 'Snacks',
                'diet' => '',
                'prijs' => '1.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),

              // Toasts
              array(
                'naam' => 'Mack & Cheese',
                'beschrijving' => 'Mackerel melt toastie',
                'allergenen' => '',
                'categorie' => 'Toasts',
                'diet' => '',
                'prijs' => '4.25',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Italian',
                'beschrijving' => 'With mozzarella, pesto & tomato',
                'allergenen' => '',
                'categorie' => 'Toasts',
                'diet' => '',
                'prijs' => '4.25',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Classic Cheese',
                'beschrijving' => 'Toasted cheese sandwich',
                'allergenen' => '',
                'categorie' => 'Toasts',
                'diet' => '',
                'prijs' => '3.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Avo on Toast',
                'beschrijving' => 'With tomato, pumpkin seeds & parsely',
                'allergenen' => '',
                'categorie' => 'Toasts',
                'diet' => '',
                'prijs' => '4.75',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Toasted Banana Bread',
                'beschrijving' => 'with yoghurt, walnuts & jam',
                'allergenen' => '',
                'categorie' => 'Toasts',
                'diet' => '',
                'prijs' => '4.75',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),

              // Salads
              array(
                'naam' => 'The Goat',
                'beschrijving' => 'Grilled goat cheese, walnuts & honey',
                'allergenen' => '',
                'categorie' => 'Salads',
                'diet' => '',
                'prijs' => '6.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'California',
                'beschrijving' => 'Salmon & avocado',
                'allergenen' => '',
                'categorie' => 'Salads',
                'diet' => '',
                'prijs' => '6.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Mista',
                'beschrijving' => 'Mozzarella & balsamic syrup',
                'allergenen' => '',
                'categorie' => 'Salads',
                'diet' => '',
                'prijs' => '5.50',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),

              // Sandwiches
              array(
                'naam' => 'Caprese',
                'beschrijving' => 'With pesto, mozzarella, tomato & rocket',
                'allergenen' => '',
                'categorie' => 'Sandwiches',
                'diet' => '',
                'prijs' => '3.75',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Salmon',
                'beschrijving' => 'Smoked ASC salmon with cream cheese',
                'allergenen' => '',
                'categorie' => 'Sandwiches',
                'diet' => '',
                'prijs' => '4.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Mackerel',
                'beschrijving' => 'Homemade mackerel salad',
                'allergenen' => '',
                'categorie' => 'Sandwiches',
                'diet' => '',
                'prijs' => '3.75',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Avo',
                'beschrijving' => 'Avocado, hummus, tomato & walnuts',
                'allergenen' => '',
                'categorie' => 'Sandwiches',
                'diet' => '',
                'prijs' => '4.00',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Hummus',
                'beschrijving' => 'With tomato & lettuce',
                'allergenen' => '',
                'categorie' => 'Sandwiches',
                'diet' => '',
                'prijs' => '3.50',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Gezond',
                'beschrijving' => 'Cheese & greens',
                'allergenen' => '',
                'categorie' => 'Sandwiches',
                'diet' => '',
                'prijs' => '3.50',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ),
              // Hot drinks
              array(
                'naam' => 'Various Teas',
                'beschrijving' => 'Keuze uit verschillende smaken',
                'allergenen' => '',
                'categorie' => 'Hot Drinks',
                'diet' => '',
                'prijs' => '2.20',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Fresh Mint Tea',
                'beschrijving' => 'Verse munt thee',
                'allergenen' => '',
                'categorie' => 'Hot Drinks',
                'diet' => '',
                'prijs' => '2.65',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Ginger Tea',
                'beschrijving' => 'Gember',
                'allergenen' => '',
                'categorie' => 'Hot Drinks',
                'diet' => '',
                'prijs' => '2.65',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Hot Chocolate',
                'beschrijving' => 'Warme chocolademelk',
                'allergenen' => '',
                'categorie' => 'Hot Drinks',
                'diet' => '',
                'prijs' => '2.75',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),array(
                'naam' => 'Chai Latte',
                'beschrijving' => 'Is vast lekker',
                'allergenen' => '',
                'categorie' => 'Hot Drinks',
                'diet' => '',
                'prijs' => '2.95',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ),
              // Coffee
              array(
                'naam' => 'Espresso',
                'beschrijving' => 'Sterke koffie',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.20',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Doppio',
                'beschrijving' => 'Lekker merk',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.80',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Americano',
                'beschrijving' => 'Koffie met veel water',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.20',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Cappuccino',
                'beschrijving' => 'Koffie met veel water',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.70',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Caffe Latte',
                'beschrijving' => 'Koffie met melk',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.95',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Latte Macchiato',
                'beschrijving' => 'Opgeschuimde melk koffie',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.95',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Cortado',
                'beschrijving' => 'Geen idee',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.60',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Flat White',
                'beschrijving' => 'Koffie met melk, again',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '2.95',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Filter Brew',
                'beschrijving' => 'Filter koffie',
                'allergenen' => '',
                'categorie' => 'Coffee',
                'diet' => '',
                'prijs' => '1.75',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),
              // Cold Drinks
              array(
                'naam' => 'Lemonaid',
                'beschrijving' => 'Limonade',
                'allergenen' => '',
                'categorie' => 'Cold Drinks',
                'diet' => '',
                'prijs' => '3.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Charitea',
                'beschrijving' => 'Koude thee',
                'allergenen' => '',
                'categorie' => 'Cold Drinks',
                'diet' => '',
                'prijs' => '3.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Schulp Juice',
                'beschrijving' => 'Wut',
                'allergenen' => '',
                'categorie' => 'Cold Drinks',
                'diet' => '',
                'prijs' => '2.75',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Milk by Arla Organic',
                'beschrijving' => 'Melk',
                'allergenen' => '',
                'categorie' => 'Cold Drinks',
                'diet' => '',
                'prijs' => '1.95',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Water by Made Blue',
                'beschrijving' => 'Simpel water',
                'allergenen' => '',
                'categorie' => 'Cold Drinks',
                'diet' => '',
                'prijs' => '1.40',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ), array(
                'naam' => 'Soda Specials',
                'beschrijving' => 'Frisdrank',
                'allergenen' => '',
                'categorie' => 'Cold Drinks',
                'diet' => '',
                'prijs' => '2.50',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),
              //Dakterras Menu
              array(
                'naam' => 'Kaartje',
                'beschrijving' => 'Entree & 6 strippen',
                'allergenen' => '',
                'categorie' => 'kaarten',
                'diet' => '',
                'prijs' => '10.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),
              array(
                'naam' => 'Kaartje Regulier',
                'beschrijving' => 'Entree, 6 strippen & snacks',
                'allergenen' => '',
                'categorie' => 'kaarten',
                'diet' => '',
                'prijs' => '17.00',
                'fotolocatie' => '',
                'chefSpecial' => '0',
                'aantalVerkocht' => '0',
              ),
              array(
                'naam' => 'Kaartje Large',
                'beschrijving' => 'Entree, 9 strippen & me...cks',
                'allergenen' => '',
                'categorie' => 'kaarten',
                'diet' => '',
                'prijs' => '27.00',
                'fotolocatie' => '',
                'chefSpecial' => '1',
                'aantalVerkocht' => '0',
              ),



            ));
    }
}
